INSERT INTO Estados (id, abrev, nombre) VALUES('1','AGUA','AGUASCALIENTES');
INSERT INTO Estados (id, abrev, nombre) VALUES('2','BAJA','BAJA CALIFORNIA');
INSERT INTO Estados (id, abrev, nombre) VALUES('3','BAJA','BAJA CALIFORNIA SUR');
INSERT INTO Estados (id, abrev, nombre) VALUES('4','CAMP','CAMPECHE');
INSERT INTO Estados (id, abrev, nombre) VALUES('5','COAH','COAHUILA DE ZARAGOZA');
INSERT INTO Estados (id, abrev, nombre) VALUES('6','COLI','COLIMA');
INSERT INTO Estados (id, abrev, nombre) VALUES('7','CHIA','CHIAPAS');
INSERT INTO Estados (id, abrev, nombre) VALUES('8','CHIH','CHIHUAHUA');
INSERT INTO Estados (id, abrev, nombre) VALUES('9','CIUD','CIUDAD DE MÉXICO');
INSERT INTO Estados (id, abrev, nombre) VALUES('10','DURA','DURANGO');
INSERT INTO Estados (id, abrev, nombre) VALUES('11','GUAN','GUANAJUATO');
INSERT INTO Estados (id, abrev, nombre) VALUES('12','GUER','GUERRERO');
INSERT INTO Estados (id, abrev, nombre) VALUES('13','HIDA','HIDALGO');
INSERT INTO Estados (id, abrev, nombre) VALUES('14','JALI','JALISCO');
INSERT INTO Estados (id, abrev, nombre) VALUES('15','MÉX','MÉXICO');
INSERT INTO Estados (id, abrev, nombre) VALUES('16','MICH','MICHOACÁN DE OCAMPO');
INSERT INTO Estados (id, abrev, nombre) VALUES('17','MORE','MORELOS');
INSERT INTO Estados (id, abrev, nombre) VALUES('18','NAYA','NAYARIT');
INSERT INTO Estados (id, abrev, nombre) VALUES('19','NUEV','NUEVO LEÓN');
INSERT INTO Estados (id, abrev, nombre) VALUES('20','OAXA','OAXACA');
INSERT INTO Estados (id, abrev, nombre) VALUES('21','PUEB','PUEBLA');
INSERT INTO Estados (id, abrev, nombre) VALUES('22','QUER','QUERÉTARO');
INSERT INTO Estados (id, abrev, nombre) VALUES('23','QUIN','QUINTANA ROO');
INSERT INTO Estados (id, abrev, nombre) VALUES('24','SAN ','SAN LUIS POTOSÃ');
INSERT INTO Estados (id, abrev, nombre) VALUES('25','SINA','SINALOA');
INSERT INTO Estados (id, abrev, nombre) VALUES('26','SONO','SONORA');
INSERT INTO Estados (id, abrev, nombre) VALUES('27','TABA','TABASCO');
INSERT INTO Estados (id, abrev, nombre) VALUES('28','TAMA','TAMAULIPAS');
INSERT INTO Estados (id, abrev, nombre) VALUES('29','TLAX','TLAXCALA');
INSERT INTO Estados (id, abrev, nombre) VALUES('30','VERA','VERACRUZ DE IGNACIO DE LA LLAVE');
INSERT INTO Estados (id, abrev, nombre) VALUES('31','YUCA','YUCATÁN');
INSERT INTO Estados (id, abrev, nombre) VALUES('32','ZACA','ZACATECAS');
